# Generated by Django 3.1.5 on 2021-02-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Tag ID')),
                ('title', models.CharField(max_length=10, verbose_name='TITLE')),
                ('content', models.TextField(verbose_name='CONTENT')),
            ],
        ),
    ]
