# Generated by Django 3.1.5 on 2021-02-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Category ID')),
                ('title', models.CharField(max_length=10, verbose_name='TITLE')),
                ('content', models.TextField(verbose_name='CONTENT')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Category ID')),
                ('name', models.CharField(max_length=10, verbose_name='TITLE')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Photo ID')),
                ('title', models.CharField(max_length=25, verbose_name='TITLE')),
                ('source', models.CharField(max_length=200, verbose_name='Image Source')),
                ('content', models.TextField(blank=True, null=True, verbose_name='CONTENT')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.member')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Category ID')),
                ('title', models.CharField(max_length=25, verbose_name='TITLE')),
                ('content', models.TextField(blank=True, null=True, verbose_name='CONTENT')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='TIME')),
                ('category_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.category')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.member')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.photo')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.tag')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.post'),
        ),
    ]
