# Generated by Django 3.1.5 on 2021-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210204_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='post',
            name='photo_id',
            field=models.ManyToManyField(to='page.Photo'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_id',
            field=models.ManyToManyField(to='page.Tag'),
        ),
    ]
