# Generated by Django 3.1.5 on 2021-02-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210204_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category_id',
            field=models.ManyToManyField(to='page.Category'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Member ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=10, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.post'),
        ),
    ]
